### ISSUE TITLE
Error opening the file. There may be a disk or file system error.

### ISSUE THREAD

**Issue by EntonyHop** [neta540/sn740_sp8_win11_install_patch#1]
Help me with this error [Error photo](https://linksharing.samsungcloud.com/jACzqyBzIkrM)

**Comment by EntonyHop** [comment]
> Help me with this error [Error photo](https://linksharing.samsungcloud.com/jACzqyBzIkrM)

I use 
DISKPART

select disk 0

select part 3

assign letter=T

exit

My usb drive with windows,  path for your .bat: "D:/patch/apply_patch.bat

Then i get this error 
x: \windows\system32>reg load HKLM\OFFLINE T: \Windows \System32\config\System
The operation completed successfully.
X: \windows\system32>reg împort X: \windows \system32\ahci_patch_offline.reg
ERROR: Error opening the file. There may be a disk or file system error.
X: \windows\system32>reg import x: \windows \system32 \pcie_link_state offline.reg
ERROR: Error opening the file. There may be a disk or file system error.
X: \windows\system32>reg unload HKLM\OFFLINE
The operation completed successfully,
X: \windows \system32>pause
Press any key to continue...

PS.: i use command promt from recovery menu, help me, please

**Comment by neta540** [comment]
Before running the script, change current directory to the folder where the script is and then run it. Example:

```bat
D:
cd D:\patch\
apply_patch.bat
```

**Comment by EntonyHop** [comment]
Please explain the whole process from beginning to end in detail, because I am a complete newbie to command promt and so on. 

DISKPART

select disk 0

select part 3

assign letter=T

exit

D:

cd D:\patch\

apply_patch.bat


Right i understand?

**Comment by neta540** [comment]
You only need to run the 3 commands in https://github.com/neta540/sn740_sp8_win11_install_patch/issues/1#issuecomment-1454852688

**Comment by EntonyHop** [comment]
God bless you! All works fine

**Comment by neta540** [comment]
You're welcome!
